# Generated by Django 5.1.7 on 2025-03-23 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_is_group_trip_tripparticipant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                help_text="Trip creator/owner",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tripparticipant",
            name="shares",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of people this participant represents (e.g. family)",
            ),
        ),
    ]
