# Generated by Django 5.1.7 on 2025-03-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expense_is_shared_expense_paid_by_contribution_and_more"),
        ("trips", "0003_alter_trip_user_alter_tripparticipant_shares"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_from_group_fund",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food"),
                    ("ACCOMMODATION", "Accommodation"),
                    ("TRANSPORT", "Transport"),
                    ("ACTIVITIES", "Activities"),
                    ("GAS", "Gas"),
                    ("CAR", "Car"),
                    ("MIC", "Miscellaneous"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expense",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trips.tripparticipant",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trips.trip"
            ),
        ),
    ]
