# Generated by Django 5.1.7 on 2025-03-28 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "expenses",
            "0003_remove_expense_created_at_remove_expense_updated_at_and_more",
        ),
        ("trips", "0003_alter_trip_user_alter_tripparticipant_shares"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="trips.trip",
            ),
        ),
    ]
